"""empty message

Revision ID: 06eccfb507e4
Revises: 7d68c813b86d
Create Date: 2022-04-12 14:41:44.674357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06eccfb507e4'
down_revision = '7d68c813b86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usual_info', sa.Column('ShortName', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usual_info', 'ShortName')
    # ### end Alembic commands ###
