"""empty message

Revision ID: 1f4f1023e404
Revises: 93498f8bc241
Create Date: 2022-04-09 23:15:28.929922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4f1023e404'
down_revision = '93498f8bc241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coins__table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins__table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ShortName', sa.VARCHAR(length=10), nullable=True),
    sa.Column('FullName', sa.VARCHAR(length=20), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('percent', sa.VARCHAR(length=10), nullable=True),
    sa.Column('marketcap', sa.VARCHAR(length=20), nullable=True),
    sa.Column('volume', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
