"""empty message

Revision ID: 2486d94cac4d
Revises: 88db7187c09e
Create Date: 2022-04-09 20:20:15.890082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2486d94cac4d'
down_revision = '88db7187c09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator_article', sa.Column('picturemidUrl', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicator_article', 'picturemidUrl')
    # ### end Alembic commands ###
