"""empty message

Revision ID: 339b0490c3ce
Revises: 1f4f1023e404
Create Date: 2022-04-09 23:16:05.935915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339b0490c3ce'
down_revision = '1f4f1023e404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins__table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ShortName', sa.String(length=10), nullable=True),
    sa.Column('FullName', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('marketcap', sa.String(length=20), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coins__table')
    # ### end Alembic commands ###
