"""empty message

Revision ID: 517dc6550eef
Revises: 66c12ab5f2a8
Create Date: 2022-04-12 14:45:56.908804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517dc6550eef'
down_revision = '66c12ab5f2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usual_info', sa.Column('MaxSupply', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usual_info', 'MaxSupply')
    # ### end Alembic commands ###
