"""empty message

Revision ID: 66c12ab5f2a8
Revises: 06eccfb507e4
Create Date: 2022-04-12 14:45:44.985403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c12ab5f2a8'
down_revision = '06eccfb507e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usual_info', 'MaxSupply')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usual_info', sa.Column('MaxSupply', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
