"""empty message

Revision ID: 88db7187c09e
Revises: ad938513f405
Create Date: 2022-04-09 20:19:23.382630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88db7187c09e'
down_revision = 'ad938513f405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator_article', sa.Column('pictureUrl', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicator_article', 'pictureUrl')
    # ### end Alembic commands ###
